"""Generate scene-card artwork for the Scene Explorer (28 scenes).

Pipelines: local FastAPI backend  POST /generate -> poll /jobs/{id} ->
GET /result/{id}  for each scene in site/js/config.js SCENE_GROUPS.

Outputs:
  site/img/scenes/s01..s28.webp        (512x512 WebP, ~30-50 KB each)
  site/js/scene-art.js                 (zh name -> /img/scenes/.. manifest)
  <temp>/scene_art_preview.png         (contact sheet for QA)

Rate limit: the backend allows RATE_PER_MIN=8 submissions per minute, so
submissions are paced to one per 9 s.  A 429 is retried after 15 s.  Existing
files are skipped, so re-runs resume cheaply; `--only 山川日出,极光雪原`
regenerates just those, `--offset N` shifts the fixed seeds.
"""
from __future__ import annotations

import os
import re
import sys
import tempfile
import time
from pathlib import Path

import requests

ROOT = Path(os.environ.get("LANDSCAPE_ROOT") or Path(__file__).resolve().parents[1])
API = os.environ.get("BACKEND_URL", "http://127.0.0.1:8001").rstrip("/")
TOKEN = os.environ.get("API_TOKEN", "")
if not TOKEN:
    sys.exit("API_TOKEN environment variable is required")

IMG_DIR = ROOT / "site" / "img" / "scenes"
MANIFEST = ROOT / "site" / "js" / "scene-art.js"
HEADERS = {"X-API-Key": TOKEN}

PACE_SECONDS = 9.0          # < 8 submissions/minute (server rate limit)
POLL_EVERY = 2.0
JOB_TIMEOUT = 300.0


def scenes_from_config() -> list[tuple[str, str]]:
    text = (ROOT / "site" / "js" / "config.js").read_text(encoding="utf-8")
    block = re.search(r"export const SCENE_GROUPS = \[(.*?)\n\];", text, re.S)
    if not block:
        sys.exit("SCENE_GROUPS block not found in config.js")
    pairs = re.findall(r"'([^']+)':\s*'([^']+)'", block.group(1))
    if not pairs:
        sys.exit("no scenes parsed from config.js")
    return pairs


def generate_one(prompt: str, seed: int) -> str:
    body = {
        "prompt": prompt, "style": "写实摄影", "res": "512", "aspect": "方",
        "steps": 24, "cfg": 7.5, "seed": seed, "sampler": "dpmpp2m_karras",
        "batch": 1, "fast": False, "highres": 0, "enhance": 0,
    }
    response = requests.post(f"{API}/generate", json=body, headers=HEADERS, timeout=30)
    if response.status_code == 429:
        raise RateLimited()
    response.raise_for_status()
    data = response.json()
    if data.get("status") == "done" and data.get("cached"):
        print(f"cache hit job={data.get('job_id')}")
    return str(data["job_id"])


class RateLimited(Exception):
    pass


def wait_done(job_id: str) -> None:
    started = time.time()
    while time.time() - started < JOB_TIMEOUT:
        response = requests.get(f"{API}/jobs/{job_id}", timeout=20)
        response.raise_for_status()
        meta = response.json()
        status = meta.get("status")
        if status == "done":
            return
        if status in ("failed", "expired", "cancelled"):
            raise RuntimeError(f"job {job_id} {status}: {meta.get('error') or ''}")
        time.sleep(POLL_EVERY)
    raise TimeoutError(f"job {job_id} did not finish in {JOB_TIMEOUT:.0f}s")


def download(job_id: str, path: Path) -> None:
    response = requests.get(f"{API}/result/{job_id}", timeout=60)
    response.raise_for_status()
    if len(response.content) < 1000:
        raise RuntimeError(f"job {job_id} result suspiciously small")
    path.write_bytes(response.content)


def write_manifest(pairs: list[tuple[str, str]]) -> None:
    entries = ",\n".join(f"  '{name}': '/img/scenes/s{index:02d}.webp'"
                         for index, (name, _) in enumerate(pairs, 1))
    text = ("// Generated by tools/gen_scene_art.py - zh scene name -> card artwork.\n"
            f"export const SCENE_ART = {{\n{entries},\n}};\n")
    with MANIFEST.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def contact_sheet(files: list[Path]) -> str:
    try:
        from PIL import Image
    except ImportError:
        return ""
    thumbs = []
    for path in files:
        if not path.exists():
            continue
        with Image.open(path) as im:
            im.load()
            thumbs.append(im.convert("RGB").resize((180, 180)))
    if not thumbs:
        return ""
    cols = 7
    rows = (len(thumbs) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * 180, rows * 180), "#0b1020")
    for index, thumb in enumerate(thumbs):
        sheet.paste(thumb, ((index % cols) * 180, (index // cols) * 180))
    out = Path(tempfile.gettempdir()) / "scene_art_preview.png"
    sheet.save(out)
    return str(out)


def main() -> int:
    only = ({s.strip() for s in sys.argv[sys.argv.index("--only") + 1].split(",")}
            if "--only" in sys.argv else None)
    offset = int(sys.argv[sys.argv.index("--offset") + 1]) if "--offset" in sys.argv else 0

    pairs = scenes_from_config()
    print(f"parsed {len(pairs)} scenes")
    IMG_DIR.mkdir(parents=True, exist_ok=True)

    pending = []
    for index, (name, prompt) in enumerate(pairs, 1):
        if only and name not in only:
            continue
        path = IMG_DIR / f"s{index:02d}.webp"
        if path.exists():
            print(f"skip   s{index:02d} {name} (exists)")
            continue
        pending.append((index, name, prompt, path))

    if not pending:
        write_manifest(pairs)
        print("nothing to generate")
        return 0

    for index, name, prompt, path in pending:
        seed = 20250000 + index + offset
        while True:
            try:
                print(f"gen    s{index:02d} {name} seed={seed}")
                job_id = generate_one(prompt, seed)
                wait_done(job_id)
                download(job_id, path)
                print(f"done   s{index:02d} {name} ({path.stat().st_size // 1024} KB)")
                break
            except RateLimited:
                print("rate limited; waiting 15 s")
                time.sleep(15)
            except (requests.RequestException, RuntimeError, TimeoutError) as error:
                print(f"FAIL   s{index:02d} {name}: {error}")
                return 1
        time.sleep(PACE_SECONDS)

    write_manifest(pairs)
    sheet = contact_sheet([IMG_DIR / f"s{i:02d}.webp" for i in range(1, len(pairs) + 1)])
    print(f"manifest written: {MANIFEST}")
    if sheet:
        print(f"contact sheet: {sheet}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
